### PR TITLE
Support for initial memory sizes.

### PR DESCRIPTION
**Pull request by youngm**
Reference: https://github.com/cloudfoundry/java-buildpack/issues/200

Basic pull request to support initial memory parameters that I hacked through really quick.  I want to confirm with the team if I'm on the right track or not.

This PR is not mergeable at present.

All integration tests pass unchanged but I still need to fix/add unit tests, do more negative testing, and generally polish.

I await feedback.

Mike

### CODE REVIEW

**Comment by cgfrost** [comment]
Comments as request in (https://github.com/cloudfoundry/java-buildpack/issues/200#issuecomment-124129973).

If your happy to go with a percentage of the calculated maximum that would be great. @Zteve has looked over the pull request and feels it could be simplified by leaving the `Allocator` out of it as the initial memory values can be calculated after the `Allocator` has finished it's work. 

Also, it would be great to specify the percentages with a `%` at the end. This will make it easier to, in addition, implement absolute initial memory values if we decide to do so (20% vs 20Mb). I think it will also make it easier to debug things in the future, staring at an applications start command and trying to figure out all the different arguments.

**Comment by youngm** [comment]
@cgfrost @Zteve Sounds good.  I'll hopefully have another basic attempt ready for your tomorrow.

**Comment by youngm** [comment]
@cgfrost @Zteve Here is another attempt.  I still need to write tests and document the code but all current tests pass.  Let me know if you think I'm on the right track or not.

**Comment by Zteve** [comment]
Hi Mike,
Thank you for this PR. I've looked at the code, and I think it is very sound. There are a few modifications we might want to make:

1. Edit the error messages a bit for accuracy (they claim, erroneously, initial values must be _less than_ 100, for example, when they can equal 100).
1. Add tests for the error conditions (you are stepping up to that already, I think).
1. Remove the knowledge of percentage values from the InitialSwitches code (should be provided with the values directly—shouldn't need to know how to derive them).
1. Consider factoring out the Switches function from Allocator altogether.

We might also think about merging the initial switches code into the standard switches code, rather than separating them out into a separate function and map, but that would be speculative, based upon what it would look like.

Are you happy to allow us to make these changes as we merge the PR in, or would you like to do them yourself beforehand?

**Comment by youngm** [comment]
@Zteve I'm on vacation today so I won't be making any changes today.  If you wish to make the changes and merge it go ahead.

Otherwise on Monday I'll attempt to address the points your making and write some tests.  Then you can modify it from there and merge it.

Thanks for helping me through this!

**Comment by cgfrost** [comment]
After the discussion over at https://github.com/cloudfoundry/java-buildpack/issues/200 we have an idea about changing the default behavior. We think this is fine as long as the 'out of the box' behavior of the buildpack doesn't change. It would make more sense for the memory calculator to not specify an initial memory value unless it is give a command line argument to do so. That way it is possible to fall back to the default JVM behaviour if you wish. At the same time I'll update the buildpack to specify `100%` as the initial memory values. That way existing behavior of the buildpack is maintained but users can easily and logically change it as they wish. What do you think?

**Comment by youngm** [comment]
@cgfrost @Zteve Here is another revision.

* Attempted to address all of @Zteve 's feedback.
* Added some integration tests.  I thought the integration tests exercised the InitialsSwitches pretty well.  I can add unit tests for InitialSwitches if you'd like.
* If no initial is configured then I don't set a switch for it.
* Added some initial minimums to keep the jvm from failing out at start because of a meaningless minimum config.

I think this PR is mergeable at this point.  Feel free to merge and tweak if you'd like.  Otherwise give me feedback and I'd be happy to make the requested changes tomorrow and try again.

**Comment by cgfrost** [comment]
@youngm We had a look over the code and it looks good to us but I'm sorry to say we didn't get around to merging it today.

**Comment by youngm** [comment]
@cgfrost Great!  I'll get started on the java-buildpack PR then.

**Comment by cgfrost** [comment]
We've made some changes to the implementation but no changes to the behavior. We will get this work finished next week and in the buildpack.

**Comment by youngm** [comment]
I have no problem with the changes.  Thanks for the help!

**Comment by cgfrost** [comment]
Not at all, sorry for being a little slow on this one.

**Pull request merged**
